image: debian

before_script:
  - apt-get update
  - apt-get install -y gcc make zlib1g-dev libhts-dev
  - gcc --version

build:
  stage: build
  script:
    - make all
    - make install
    - make -C test
    - test/ptest2 test/3881.pbwt 0.4 101 0 79
  only:
    - tags
