image: debian:latest

before_script:
  - apt-get update
  - apt-get install -y gcc make zlib1g-dev libhts-dev git
  - git clone https://popgendad@gmail.com:${CI_JOB_TOKEN}@gitlab.com/evolgen/libplink_lite.git
  - cd libplink_lite
  - make
  - make install

build:
  stage: build
  script:
    - make all
    - make install
    - make -C test
    - test/ptest2 test/HumanOriginsExample.pbwt 0.5 200 0 729
  only:
    - tags
