image: debian

before_script:
  - apt-get update
  - apt-get install -y gcc make zlib1g-dev libhts-dev
  - gcc --version

build:
  stage: build
  script:
    - make
    - make install
    - make -C test
    - test/ptest test/3881.pbwt 101
  only:
    - tags
